# Generated by Django 5.2.14 on 2026-05-24 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0003_personalizeddosage_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1)),
                ('height', models.FloatField(blank=True, null=True, verbose_name='키(cm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='몸무게(kg)')),
                ('conditions', models.TextField(blank=True, verbose_name='지병')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='임신 여부')),
                ('is_breastfeeding', models.BooleanField(default=False, verbose_name='수유 여부')),
                ('current_medicines', models.ManyToManyField(blank=True, to='medicines.medicine', verbose_name='복용 중인 약')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
            },
        ),
    ]
