# Generated by Django 5.2.14 on 2026-05-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='성분명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '성분',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('category', models.CharField(choices=[('OTC', '일반의약품'), ('ETC', '전문의약품'), ('SUPP', '건강기능식품')], max_length=10, verbose_name='분류')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='제조사')),
                ('usage', models.TextField(verbose_name='용도/효능')),
                ('dosage', models.TextField(verbose_name='섭취/복용법')),
                ('storage', models.TextField(verbose_name='보관법')),
                ('precautions', models.TextField(verbose_name='주의사항')),
                ('side_effects', models.TextField(verbose_name='부작용')),
                ('contraindications', models.TextField(verbose_name='금기 조건')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '약품',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CAUTION', '병용 주의'), ('FORBIDDEN', '병용 금기')], max_length=20, verbose_name='상호작용 수준')),
                ('description', models.TextField(verbose_name='상호작용 설명')),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='medicines.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='medicines.medicine')),
            ],
            options={
                'verbose_name': '상호작용',
            },
        ),
        migrations.CreateModel(
            name='MedicineIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, verbose_name='함량')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.ingredient')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
            ],
            options={
                'verbose_name': '약품 성분',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='ingredients',
            field=models.ManyToManyField(through='medicines.MedicineIngredient', to='medicines.ingredient', verbose_name='성분'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1)),
                ('height', models.FloatField(blank=True, null=True, verbose_name='키(cm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='몸무게(kg)')),
                ('conditions', models.TextField(blank=True, verbose_name='지병')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='임신 여부')),
                ('is_breastfeeding', models.BooleanField(default=False, verbose_name='수유 여부')),
                ('current_medicines', models.ManyToManyField(blank=True, to='medicines.medicine', verbose_name='복용 중인 약')),
            ],
            options={
                'verbose_name': '사용자 프로필',
            },
        ),
    ]
