# Generated by Django 5.2.14 on 2026-05-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedDosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('infant', '영아 (0~23개월)'), ('child', '소아 (2~11세)'), ('teen', '청소년 (12~17세)'), ('adult', '성인 (18~64세)'), ('elderly', '고령자 (65세 이상)')], max_length=10, verbose_name='연령 그룹')),
                ('dosage_info', models.TextField(verbose_name='복용량/방법')),
                ('special_precautions', models.TextField(blank=True, verbose_name='해당 그룹 특이 주의사항')),
                ('is_contraindicated', models.BooleanField(default=False, verbose_name='해당 그룹 금기 여부')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_dosages', to='medicines.medicine', verbose_name='약품')),
            ],
            options={
                'verbose_name': '맞춤 복용 정보',
                'unique_together': {('medicine', 'age_group')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
